name: Build

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push (no tags)
        uses: docker/build-push-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${REPO}:latest
            ghcr.io/${REPO}:${{ github.sha }}

      - name: Build and push (tags)
        uses: docker/build-push-action@v4
        if: github.ref != 'refs/heads/main'
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${REPO}:latest
            ghcr.io/${REPO}:${{ github.sha }}
            ghcr.io/${REPO}:${{ github.ref_name }}
